### ISSUE TITLE
FL Studio Scripting - Piano roll

### ISSUE THREAD

**Issue by smrde** [MiguelGuthridge/FL-Studio-API-Stubs#33]
Can you please add piano roll Scripting?
import flpianoroll

Thanks

**Comment by MiguelGuthridge** [comment]
This is on my todo list, and I'll hopefully be able to get to it over the holidays. Sadly I've been super busy with university and other work recently, so I haven't had as much time to keep this project up-to-date as I would like to have. 

As a side note, if you know Python and can write some stub code, I'd massively appreciate a pull request that implements it, since that would mean that it'd be sorted out far quicker!

**Comment by MiguelGuthridge** [comment]
Hello, @smrde! Thanks for your patience. I've added the `flpianoroll` module in the latest release, `v33.2.0`! Enjoy, and let me know if there are any issues!
